# Generated by Django 5.1.1 on 2024-11-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_alter_flight_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='last_name',
        ),
        migrations.AddField(
            model_name='passenger',
            name='username',
            field=models.CharField(default='default_user', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
